### ISSUE TITLE
Getting chart checks working at another site

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1475]
Hi @rembishj,

The config file appears to be working as expected:

![image](https://user-images.githubusercontent.com/6559099/113646307-ec2f9180-96cb-11eb-98a9-ef078809e5cd.png)

It is picking up my Mosaiq configuration. However when I upload the demo DICOM data from `C:\Users\sbiggs\.pymedphys\data\mu-density-gui-e2e-data\pymedphys-gui-demo\inputs\Monaco\FocalData_for_site_blue\DCMXprtFile` the application does not respond (nor does it give me feedback about what I may have done wrong).

Cheers,
Simon

**Comment by SimonBiggs** [comment]
I have attached the DICOM files below for your own testing:

[DCMXprtFile.zip](https://github.com/pymedphys/pymedphys/files/6261431/DCMXprtFile.zip)

**Comment by rembishj** [comment]
Here's where the problem is:

https://github.com/pymedphys/pymedphys/blob/6d040b75cfd16358e9eba5914b5bb406ee92a3f2/lib/pymedphys/_experimental/streamlit/apps/transfer_check.py#L47-L65

I had been defining the file type based on our institutions naming convention. I will look into a better approach to this.

**Comment by SimonBiggs** [comment]
So there's a new error, but that's usually a good thing 🙂. New error often means the old error is fixed 🙂.

So the new error happens after uploading the DICOM files:

![image](https://user-images.githubusercontent.com/6559099/113788680-e34cc780-9780-11eb-9eab-0c79d60c427d.png)

A close up of the picture of the error message is below:

![image](https://user-images.githubusercontent.com/6559099/113788662-d8923280-9780-11eb-98b0-201b439cc6c8.png)
  
The error message copied in as text:

```python
KeyError: 0
Traceback:
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\streamlit\script_runner.py", line 333, in _run_script
    exec(code, module.__dict__)
File "C:\Users\pexit\git\pymedphys\lib\pymedphys\_app.py", line 24, in <module>
    main()
File "C:\Users\pexit\git\pymedphys\lib\pymedphys\_app.py", line 20, in main
    index.main()
File "C:\Users\pexit\git\pymedphys\lib\pymedphys\_streamlit\index.py", line 149, in main
    application_function()
File "C:\Users\pexit\git\pymedphys\lib\pymedphys\_experimental\streamlit\apps\transfer_check.py", line 85, in main
    verify_basic_patient_info(dicom_table, mosaiq_table, mrn)
File "C:\Users\pexit\git\pymedphys\lib\pymedphys\_experimental\streamlit\apps\transfer_check.py", line 202, in verify_basic_patient_info
    mosaiq_table.loc[0, "first_name"] + " " + mosaiq_table.loc[0, "last_name"]
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexing.py", line 786, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\generic.py", line 3493, in xs
    loc = self.index.get_loc(key)
File "C:\Users\pexit\AppData\Local\pypoetry\Cache\virtualenvs\pymedphys-kNpW21K4-py3.7\lib\site-packages\pandas\core\indexes\range.py", line 357, in get_loc
    raise KeyError(key) from err
```

**Comment by rembishj** [comment]
Do you have a patient with that MRN in your Mosaiq? Because from the error it looks like you do not, and the error comes when trying to pull the first and last name.

**Comment by SimonBiggs** [comment]
> Do you have a patient with that MRN in your Mosaiq? Because from the error it looks like you do not, and the error comes when trying to pull the first and last name.

Yup, I do have that Patient ID within our Mosaiq.

**Comment by rembishj** [comment]
Hmm interesting... not sure why it isn't wanting to play nice there. I would try importing just this function and see if you are even getting any values returned:

https://github.com/pymedphys/pymedphys/blob/a6f9e602871fe2cf2a72cf35e5d665eb2f3799b2/lib/pymedphys/_experimental/chartchecks/helpers.py#L166

**Comment by SimonBiggs** [comment]
> I would try importing just this function and see if you are even getting any values returned

Here's a little interactive prompt of playing with that function:

```python
C:\Users\sbiggs\git\pymedphys [doctors-notes-search ≡]> poetry run python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymedphys._experimental.chartchecks.helpers import get_all_mosaiq_treatment_data
>>> import pymedphys
>>> connections = pymedphys.mosaiq.connect("msqsql")
>>> get_all_mosaiq_treatment_data(connections, 979797)
Traceback (most recent call last):
  File "src\pymssql.pyx", line 450, in pymssql.Cursor.execute
  File "src\_mssql.pyx", line 1070, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1102, in _mssql.MSSQLConnection.execute_query
  File "src\_mssql.pyx", line 1300, in _mssql.MSSQLConnection.get_result
  File "src\_mssql.pyx", line 1648, in _mssql.check_cancel_and_raise
  File "src\_mssql.pyx", line 1690, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (245, b"Conversion failed when converting the varchar value '00017R' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sbiggs\git\pymedphys\lib\pymedphys\_experimental\chartchecks\helpers.py", line 259, in get_all_mosaiq_treatment_data
    connection=connection, query=sql_string, parameters={"patient_id": mrn}
  File "C:\Users\sbiggs\git\pymedphys\lib\pymedphys\_mosaiq\api.py", line 191, in execute
    cursor.execute(query=query, parameters=parameters)
  File "C:\Users\sbiggs\git\pymedphys\lib\pymedphys\_mosaiq\connect.py", line 85, in execute
    self._cursor.execute(query, parameters)
  File "src\pymssql.pyx", line 468, in pymssql.Cursor.execute
pymssql.OperationalError: (245, b"Conversion failed when converting the varchar value '00017R' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
>>> get_all_mosaiq_treatment_data(connections, "979797")
      mrn  Pat_ID first_name last_name        dob  ... create_id  field_approval site_ID site_setup_ID         rx
0  979797   30136       TEST   PHYSICS 2020-04-29  ...      None            None   16274         10661   0.0Xrays

[1 rows x 65 columns]
>>> result = get_all_mosaiq_treatment_data(connections, "979797")
>>> result.to_csv('out.csv')
```

The CSV produced from that is within the following zip:

[out.zip](https://github.com/pymedphys/pymedphys/files/6276356/out.zip)

**Comment by rembishj** [comment]
Good call. Does that fix the initial keyerror problem now?
