### ISSUE TITLE
Building a PyOxidizer binary install of PyMedPhys

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1556]
I plan to create an executable for the PyMedPhys CLI (which also includes the GUI). This will install without admin privileges on Windows. I will also create an install for MacOS and Linux. I have the option to manually sign the release executable with my Radiotherapy AI enterprise license declaring that I have overseen that particular build and guaranteeing that it isn't modified before installation after the signing.

When this executable is installed an option is provided to automatically have PyMedPhys added to the PATH.

I will start with Windows, and I will detail the key steps within this issue so that others can follow along and replicate if need be. Of note, this is essentially bundling a Streamlit application into a standalone executable, so those who are trying to do this, following my steps here may be helpful. This in particular has been requested over in the [Streamlit forums](https://discuss.streamlit.io/t/using-pyinstaller-or-similar-to-create-an-executable/902/32?u=simonbiggs).

I am going to detail here the process I go through (warts and all). I figure it might be beneficial for someone to have a read through and see my process. This is heavily inspired by how @simonw documents his work on datasette-app, which helped me through some issues recently:

https://github.com/simonw/datasette-app/issues/22

Also, if one of my desires for PyMedPhys is that it becomes a way that people can learn how to code, it helps to be able to read someone struggling through these concepts.

---

I'm going to label this issue as "teaching", and this is the approach I will take. My primary audience is people who are wanting to learn, so I am going to step into "teacher mode", and write from that frame of reference. I recognise that writing out an issue like this will cost a reasonable amount of time. It is my hope that others can benefit from it. Please let me know if you do find this beneficial as whether or not I flesh out more code contributions like this will be directly dependent on that feedback.

---

To see this latest code from this work, see https://github.com/pymedphys/pymedphys/pull/1557

**Comment by SimonBiggs** [comment]
Created an initial commit for the pyoxidizer build file:

https://github.com/pymedphys/pymedphys/blob/87ee7b6e0bdbc67f2c93e15345b14338f8c5ea90/pyoxidizer.bzl#L1-L78

Also added PyOxidizer as a dev dependency:

https://github.com/pymedphys/pymedphys/blob/4f198f1d8944a4dcfeee9bb8daf63e565d981499/pyproject.toml#L152

On a first pass I got the following error:

```
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: obtaining embedded python context
    3: converting debugpy._vendored.pydevd._pydev_imps._pydev_SimpleXMLRPCServer to resource
    4: compiling relative path module bytecode
    5: compiling error: invalid syntax (debugpy._vendored.pydevd._pydev_imps._pydev_SimpleXMLRPCServer, line 263)
  --> ./pyoxidizer.bzl:59:12
   |
59 |       return exe.to_wix_msi_builder(
   |  ____________^
60 | |         # Simple identifier of your app.
61 | |         "pymedphys",
62 | |         # The name of your application.
...  |
67 | |         "PyMedPhys Contributors",
68 | |     )
   | |_____^ PythonExecutable.to_file_manifest()


error: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: obtaining embedded python context
    3: converting debugpy._vendored.pydevd._pydev_imps._pydev_SimpleXMLRPCServer to resource
    4: compiling relative path module bytecode
    5: compiling error: invalid syntax (debugpy._vendored.pydevd._pydev_imps._pydev_SimpleXMLRPCServer, line 263)
```

**Comment by SimonBiggs** [comment]
I then attempted a bit of trial-and-error with the following changes:

https://github.com/pymedphys/pymedphys/pull/1557/commits/f8eb66dd2cb97db4536317c85be3d0ff33dc5fd4

But to no avail.

**Comment by SimonBiggs** [comment]
Dropped a comment over on the PyOxidizer issue board.

https://github.com/indygreg/PyOxidizer/issues/453

They might not get the chance to help, but certainly no harm in asking people who are significantly more experienced with these tools than I am. (as long as it is understood that they certainly have no obligation to help :) )

**Comment by SimonBiggs** [comment]
Given this problem appears to be a dependency problem I am going to undergo a bit of a sweeping change / pivot to my scope. The PyMedPhys CLI has a few more heavily used tools that are not very dependency heavy:

* The icom listener -- https://docs.pymedphys.com/cli/ref/icom.html
* The pinnacle export tool -- https://docs.pymedphys.com/cli/ref/pinnacle.html
* And the DICOM anonymiser -- https://docs.pymedphys.com/cli/ref/dicom.html#anonymise

An exe that just has enough dependencies to run those tools is still going to be very useful in the wild. This is part of the 

> To get the same effect in code, we're looking for something that gets us from a requirement to some aspect of the final system quickly, visibly, and repeatably.
>
> Tracer code is not disposable: you write it for keeps. It contains all the error checking, structuring, documentation, and self-checking that any piece of production code has. It simply is not fully functional. However, once you have achieved an end-to-end connection among the components of your system, you can check how close to the target you are, adjusting if necessary. Once you're on target, adding functionality is easy.

-- [The Pragmatic Programmer page 49](https://www.google.com.au/books/edition/The_Pragmatic_Programmer/5wBQEp6ruIAC?hl=en&gbpv=1&pg=PA49&printsec=frontcover)

Essentially, we can use these smaller versions of a PyMedPhys exe to have something that is useful, that people can install, run, and give feedback on, we can still flesh out the automated build and testing system using this "shrunk down version", and it is better to do this, and get that user feedback, than to spend the same amount of time struggling trying to get a full "complete" system working.

**Comment by SimonBiggs** [comment]
The place in PyMedPhys where toml is being used is the following:

https://github.com/pymedphys/pymedphys/blob/164a7a5c6051ab4c8fd6efdb79c3bfb0684b65df/lib/pymedphys/_config.py#L30-L45

I could choose to make it so that this falls back gracefully if toml isn't found, but toml is quite a light dependency, and it is handy to have the capacity for the config file to be used to configure the icom logging if so desired.

So, I added in a new "CLI" extras, adding a dependency to a new extras in PyMedPhys involves just editing the `# groups = ` comment in the `pyproject.toml` file as so:

https://github.com/pymedphys/pymedphys/pull/1557/commits/645ad2cbf7a3ae8edd4c9197079997482a6cdc27#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

Then, when running `poetry run pymedphys dev propagate` this automatically generates the poetry extras section:

https://github.com/pymedphys/pymedphys/pull/1557/commits/880c81552db6e8b118f276b5f7440f6dfe58e7c7#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by SimonBiggs** [comment]
In the previous commit I also created a new `requirements-cli.txt` (at some point maybe these should be moved into their own folder...).

I then added this to the build config:

https://github.com/pymedphys/pymedphys/pull/1557/commits/0902f1ed32e255b4bf1495d2800cc90338749d2b

Ran:

```
poetry run pyoxidizer build install
```

Then ran:

```
./build/dist/pymedphys icom listen 127.0.0.1 scratch
```

...and ... same error:

```
simon@dads-desktop:~/git/pymedphys$ ./build/dist/pymedphys icom listen 127.0.0.1 scratch
Traceback (most recent call last):
  File "pymedphys._vendor.apipkg", line 238, in __getattribute__
  File "pymedphys._vendor.apipkg", line 216, in getmod
  File "pymedphys._vendor.apipkg", line 103, in importobj
ModuleNotFoundError: No module named 'toml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy", line 197, in _run_module_as_main
  File "runpy", line 87, in _run_code
  File "pymedphys.__main__", line 19, in <module>
  File "pymedphys.cli", line 137, in pymedphys_cli
  File "pymedphys.cli", line 73, in get_logging_config
  File "pymedphys._config", line 40, in get_config
  File "pymedphys._vendor.apipkg", line 248, in __getattribute__
ModuleNotFoundError: 
                    PyMedPhys was unable to import "toml.load".
                    The easiest way to fix this issue is to use the "[user]"
                    option when installing PyMedPhys. For example,
                    with pip this can be done by calling
                    "pip install pymedphys[user]==0.38.0-dev4".
```

Ahh... wrong dependency... `import toml` is different to `import tomlkit`... hmm... I really should only be using one of those. Anyway, for now I'll just point to the right dep within the CLI extras (https://github.com/uiri/toml).

**Comment by SimonBiggs** [comment]
Alright, so we need to be able to test that indeed this listener works. So, we need to be able to mock a Linac streaming. Here is a scenario where in the past I made regular use of manual testing. I no longer work at a Radiotherapy clinic so I don't have that benefit anymore. And... my reliance on manual testing here resulted in bugs like that detailed above to creep in.

So, first thing first, let's mock a Linac iCOM stream.

**Comment by SimonBiggs** [comment]
Within PyMedPhys there is already a set of testing data for iCOM, it is saved within the end-to-end GUI testing suite. To download this data do the following:

`poetry run ipython`

```python
simon@dads-desktop:~/git/pymedphys$ poetry run ipython
Python 3.9.7 (default, Sep 21 2021, 06:50:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pymedphys._data import download

In [2]: paths = download.zip_data_paths('metersetmap-gui-e2e-data.zip')

In [4]: paths[0:5]
Out[4]: 
[PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/baseline/png/979797 DICOM (VMAT) vs iCOM (20200429_075043)/diff.png'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/baseline/png/979797 DICOM (VMAT) vs iCOM (20200429_075043)/evaluation.png'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/baseline/png/979797 DICOM (VMAT) vs iCOM (20200429_075043)/gamma.png'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/baseline/png/979797 DICOM (VMAT) vs iCOM (20200429_075043)/reference.png'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/baseline/png/989898 Monaco (3ABUT) vs iCOM (20200429_074729)/diff.png')]
```

We just want the iCOM files, they end in `.xz`, so let's filter by that:

```python
In [10]: icom_paths = [path for path in paths if path.suffix == '.xz']
    ...: icom_paths
Out[10]: 
[PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_075043.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_075404.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_075624.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_075920.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_080245.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/979797_PHYSICS, TEST/20200429_080624.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/989898_PHYSICS, MOCK/20200427_080239.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/989898_PHYSICS, MOCK/20200429_074444.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/989898_PHYSICS, MOCK/20200429_074559.xz'),
 PosixPath('/mnt/data/.pymedphys/data/metersetmap-gui-e2e-data/pymedphys-gui-demo/inputs/iCOM/patients/989898_PHYSICS, MOCK/20200429_074729.xz')]
```

**Comment by SimonBiggs** [comment]
Now we need to take this data and stream it on the iCOM port. After a quick google of [python server data on a socket](https://www.google.com/search?q=python+serve+data+on+a+socket) I found the following example:

https://realpython.com/python-sockets/#echo-server

The iCOM port is `1706`, and all we need to do is take the data in those files and stream them across the connection. The iCOM stream files are saved in an `lzma` compressed file format. Here is some example code loading them up:

https://github.com/pymedphys/pymedphys/blob/164a7a5c6051ab4c8fd6efdb79c3bfb0684b65df/lib/pymedphys/_streamlit/apps/metersetmap/_icom.py#L28-L41

So, let's load up those files into one big byte stream:

```python
In [13]: import lzma

In [14]: def load_icom_stream(icom_path):
    ...:     with lzma.open(icom_path, "r") as f:
    ...:         contents = f.read()
    ...: 
    ...:     return contents
    ...: 
    ...: 
    ...: def load_icom_streams(icom_paths):
    ...:     icom_streams = []
    ...: 
    ...:     for icom_path in icom_paths:
    ...:         icom_streams += [load_icom_stream(icom_path)]
    ...: 
    ...:     return icom_streams
    ...: 

In [15]: byte_stream = load_icom_streams(icom_paths)
```

We then start a server that blocks until a connection is made, ready to "blast" the client with all of the files all at once... let's see how this goes...

```python
In [16]: import socket
    ...: 
    ...: with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    ...:     s.bind(('127.0.0.1', 1706))
    ...:     s.listen()
    ...:     conn, addr = s.accept()
    ...:     with conn:
    ...:         conn.sendall(byte_stream)
    ...: 
```

Then in another command prompt I run:

```
./build/dist/pymedphys icom listen 127.0.0.1 scratch
```

And the iCOM listener didn't error out anymore (yay), but the original socket server had the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-e056a49ddad0> in <module>
      6     conn, addr = s.accept()
      7     with conn:
----> 8         conn.sendall(byte_stream)
      9 

TypeError: a bytes-like object is required, not 'list'

```

Ooops, my "byte_stream" was actually a list with bytes in them:

```python
In [17]: type(byte_stream)
Out[17]: list

In [18]: type(byte_stream[0])
Out[18]: bytes
```

So let's try the following instead:

```python
In [19]: import socket
    ...: 
    ...: with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    ...:     s.bind(('127.0.0.1', 1706))
    ...:     s.listen()
    ...:     conn, addr = s.accept()
    ...:     with conn:
    ...:         for data in byte_stream:
    ...:             conn.sendall(data)
    ...: 
```

And this produced the following error:

```python
simon@dads-desktop:~/git/pymedphys$ ./build/dist/pymedphys icom listen 127.0.0.1 scratch
...
Traceback (most recent call last):
  File "pymedphys._icom.listener", line 97, in listen_cli
    listen(args.ip, args.directory)
  File "pymedphys._icom.listener", line 83, in listen
    archive_by_patient(ip, data_to_save)
  File "pymedphys._icom.listener", line 50, in archive_by_patient
    patient_icom_data.update_data(ip, data)
  File "pymedphys._icom.patients", line 130, in update_data
    raise ValueError("Data stream appears to be arriving out of order")
ValueError: Data stream appears to be arriving out of order
```

Ahh, that's an interesting error, doing a search through the code base it comes from the following:

https://github.com/pymedphys/pymedphys/blob/164a7a5c6051ab4c8fd6efdb79c3bfb0684b65df/lib/pymedphys/_icom/patients.py#L120-L133

It's quite important that the iCOM listener doesn't misbehave, so, if the received data is anything that it doesn't expect it simply stops and chucks a hissy fit. Every iCOM data item has an index, this check here is making sure that the currently received data item is incremented by exactly one compared to the most recently received data item. Since we just threw all the files at it, we "skipped" a lot of data. That's something the iCOM listener doesn't expect, so at risk of providing spurious data results it instead crashes loudly.

**Comment by SimonBiggs** [comment]
So, instead, let's just send the one file:

```ipython
In [20]: import socket
    ...: 
    ...: with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    ...:     s.bind(('127.0.0.1', 1706))
    ...:     s.listen()
    ...:     conn, addr = s.accept()
    ...:     with conn:
    ...:         conn.sendall(byte_stream[0])
    ...: 
    ...: 
```

Which resulted in the following:

```
simon@dads-desktop:~/git/pymedphys$ ./build/dist/pymedphys icom listen 127.0.0.1 scratch
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
2021-10-08 14:26:17 WARNING  Skip this data item, duplicate of previous data item.
...
```

So, deleted the old 'scratch' file so that the duplicate data was gone and reran the server and listener:

```ipython
In [1]: import lzma
   ...: import socket
   ...: from pymedphys._data import download
   ...: 
   ...: paths = download.zip_data_paths('metersetmap-gui-e2e-data.zip')
   ...: icom_paths = [path for path in paths if path.suffix == '.xz']
   ...: 
   ...: def load_icom_stream(icom_path):
   ...:     with lzma.open(icom_path, "r") as f:
   ...:         contents = f.read()
   ...: 
   ...:     return contents
   ...: 
   ...: data = load_icom_stream(icom_paths[0])
   ...: 
   ...: with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
   ...:     s.bind(('127.0.0.1', 1706))
   ...:     s.listen()
   ...:     conn, addr = s.accept()
   ...:     with conn:
   ...:         conn.sendall(data)
```

**Comment by SimonBiggs** [comment]
It's at this point I wanted to be able to see if the pytest passes when called from within the built binary. So, I create a tests requirements.txt:

https://github.com/pymedphys/pymedphys/pull/1557/commits/eba1211e9ad3b89dace6dfa13e6e778b18a843bc#diff-cb7f4cc4be7c9f82ab41549f586ffd4992e3a07005abc527a81b7b64ff15e6bc

Then built the binary with:

```
poetry run pyoxidizer build install
```

And then tried running the tests as:

```
./build/dist/pymedphys dev tests -k icom_cli -s
```

This got the following error:

```
simon@dads-desktop:~/git/pymedphys$ ./build/dist/pymedphys dev tests -k icom_cli -s
Running pytest with cwd set to:
    /home/simon/git/pymedphys/build/dist/lib/pymedphys

error: unrecognized arguments: -k icom_cli -s
usage: pymedphys [-h] [-v] [-d] {dicom,experimental,trf,dev,zenodo,icom,gui,streamlit} ...

positional arguments:
  {dicom,experimental,trf,dev,zenodo,icom,gui,streamlit}
    dicom               A toolbox for the manipulation of DICOM files.
    experimental        Experimental tools.
    trf                 A toolbox to work with the Elekta Linac ``.trf`` binary log files.
    icom                Utilities for interfacing with Elekta's iCom protocol.
    gui                 Run the PyMedPhys GUI.
    streamlit           Wrapper for streamlit CLI

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Be verbose
  -d, --debug           Print debugging statements
```

This is because the "pymedphys" binary is being called instead of Python, and pytest can't run. So, fixed this with the following commit:

https://github.com/pymedphys/pymedphys/pull/1557/commits/595f150fe5643201f0e7e997c77cec97bb4239fb

**Comment by SimonBiggs** [comment]
To attempt to fix this, I have a suspicion that this might be because pyoxidizers import system is clashing with pytest. To test this hypothesis I disabled the pyoxidizer importer:

https://github.com/pymedphys/pymedphys/pull/1557/commits/78b8ecb3a56eddeab87a12b2ff6971310ce32e35

I then rebuilt with `poetry run pyoxidizer build install` and reran `./build/dist/pymedphys dev tests -k icom_cli -s`. This time a new error:

```
simon@dads-desktop:~/git/pymedphys$ ./build/dist/pymedphys dev tests -k icom_cli -s
Running pytest with cwd set to:
    /home/simon/git/pymedphys/build/dist/lib/pymedphys

Test session starts (platform: linux, Python 3.9.6, pytest 6.2.4, pytest-sugar 0.9.4)
rootdir: /home/simon/git/pymedphys
plugins: sugar-0.9.4, rerunfailures-10.1, hypothesis-5.49.0
collecting ... No preset version installed for command pymedphys
Please install a version by running one of the following:

asdf install python 3.9.7

or add one of the following versions in your config file at /home/simon/.tool-versions
python 3.9.2
python 3.8.8
python 3.9.6
```

That is quite a promising error! That means it was the pyoxidizer import that was causing issues previously :). So that previous one is fixed... new problem now... The rest of that text actually just means that the command `pymedphys` was attempted but it didn't work, if couldn't find it on my path...

**Comment by SimonBiggs** [comment]
So, the issue is that the built pymedphys executable wasn't findable on the path. So, I made it so that if within the pyoxidizer build then add the binary to the path. This was undergone in the following two commits:

https://github.com/pymedphys/pymedphys/pull/1557/commits/38c2e5c583bd75369c5daba7fe152fc5104a7253
https://github.com/pymedphys/pymedphys/pull/1557/commits/d2bc8cf8dd402baf070577bf8a7129bcae97bba1

**Comment by SimonBiggs** [comment]
Having a look at the following:

https://github.com/indygreg/PyOxidizer/blob/4d9007221087cd99e748fef9b6d5361fd2690cd2/tugger/src/starlark/wix_installer.rs#L544-L560

It appears that potentially [the docs](https://pyoxidizer.readthedocs.io/en/latest/tugger_starlark_type_wix_installer.html?highlight=WiXInstaller#starlark_tugger.WiXInstaller.add_simple_installer) might be missing the id parameter. So tried using an id parameter.

See https://github.com/pymedphys/pymedphys/pull/1557/commits/a52eb773d76334ae938b768f2e424c40ff648cbb

**Comment by SimonBiggs** [comment]
So, that "worked". New error is:

```
error LGHT0094 : Unresolved reference to symbol 'Directory:LocalAppDataFolder' in section 'Fragment:'.
```

**Comment by SimonBiggs** [comment]
So, this project did get so close to crossing the finish line and, it would be quite helpful to have an "easy distribution" option for PyMedPhys which can be downloaded from a PyMedPhys landing page (no python needed...).

I had trouble with creating a WIX installer. Potentially, for now we can just create a zip file. And then, in the future we can either try WIX without pyoxidizer, or try some other installer.

Nevertheless, having a zipped up portable version of PyMedPhys for a range of operating systems would still be a helpful goal. So, that's where we'll attempt to go from here.

**Comment by SimonBiggs** [comment]
I use `asdf` locally to manage my various programming languages. And even though pyoxidizer can be installed through pip, it's preferred approach is installed as a rust create. So I am going to go that path:

```
asdf install rust 1.61.0
asdf global rust 1.61.0

asdf reshim
cargo install pyoxidizer
asdf reshim
```

I then simplified and tweaked the build config file:

https://github.com/pymedphys/pymedphys/pull/1661/commits/7110a9e2ae43c03d399ec8473a684c96de6d6bbf

And ran:

```
pyoxidizer build
```

**Comment by SimonBiggs** [comment]
This build got the following error:

```
...
writing /tmp/pyoxidizeroiDSDb/pymedphys/.cargo/config
writing /tmp/pyoxidizeroiDSDb/pymedphys/Cargo.lock
writing /tmp/pyoxidizeroiDSDb/pymedphys/build.rs
writing /tmp/pyoxidizeroiDSDb/pymedphys/src/main.rs
writing /tmp/pyoxidizeroiDSDb/pymedphys/pyoxidizer.bzl
writing /tmp/pyoxidizeroiDSDb/pymedphys/pymedphys.exe.manifest
writing /tmp/pyoxidizeroiDSDb/pymedphys/pymedphys-manifest.rc
error: error calling build(): Runtime(RuntimeError { code: "PYOXIDIZER_PYTHON_EXECUTABLE", message: "building Python executable\n\nCaused by:\n    0: building executable with Rust project\n    1: obtaining embedded python context\n    2: converting libjpeg.src.libjpeg.doxyfilter to resource\n    3: compiling relative path module bytecode\n    4: compiling error: Missing parentheses in call to 'print'. Did you mean print(...)? (libjpeg.src.libjpeg.doxyfilter, line 25)", label: "PythonExecutable.build()" })
```

Tracking it down the issue is within `libjpeg.src.libjpeg.doxyfilter` which is within the following package:

https://github.com/pydicom/pylibjpeg-libjpeg

And tracking to that file I see the following:

https://github.com/thorfdbg/libjpeg/blob/ea6315164b1649ff932a396b7600eac4bffcfaba/doxyfilter.py

It looks like the file was updated last month with the following comment:

![image](https://user-images.githubusercontent.com/6559099/173166237-585bf317-1302-4fab-a50d-224aec81cf6c.png)

And tracking back, @scaramallion is on top of it and has updated the main branch to match:

https://github.com/pydicom/pylibjpeg-libjpeg/tree/master/libjpeg/src

![image](https://user-images.githubusercontent.com/6559099/173166186-ebd37d8c-f66e-4e2a-86cb-d1295979b94e.png)

So this should be fixed on pypi once pylibjpeg goes through its next release.
