### ISSUE TITLE
DICOM experimental anonymise not working with Python 3.11

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1793]
Hi @sjswerdloff,

With Python 3.11 I get the following issue:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/__init__.py", line 134, in pymedphys_cli
    parser = define_parser()
             ^^^^^^^^^^^^^^^
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/__init__.py", line 44, in define_parser
    experimental_cli(subparsers)
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/experimental/__init__.py", line 27, in experimental_cli
    dicom_cli(experimental_subparsers)
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/experimental/dicom.py", line 28, in dicom_cli
    anonymise(dicom_subparsers)
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/experimental/dicom.py", line 34, in anonymise
    parser = dicom.anonymise(dicom_subparsers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/git/pymedphys/lib/pymedphys/cli/dicom.py", line 136, in anonymise
    parser = dicom_subparsers.add_parser("anonymise", help=("Anonymise DICOM files."))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/.asdf/installs/python/3.11.3/lib/python3.11/argparse.py", line 1192, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument dicom: conflicting subparser: anonymise
``` 

Right now I'm trying to do a pymedphys upgrade, and if there are experimental components that are causing upgrade difficulties I am opting to remove them for now.

More than happy for this experimental CLI to come back, but for now I will remove it in order to continue forward with my dep upgrade.

**Comment by sjswerdloff** [comment]
OK.  I will try to get to this on the weekend.
But if I rename it to pseudonymise and change the command line argument, I will eliminate the --pseudo.

**Comment by SimonBiggs** [comment]
Don't feel like you need to do it this weekend. I just want the repo back into a state where the tests are passing and we don't have all the following security issues:

![image](https://user-images.githubusercontent.com/6559099/233342210-f384e0d6-a50b-4d8a-acfe-14648b331446.png)

**Comment by sjswerdloff** [comment]
Oh...
You should have led with "we need to update because we have a slew of dependencies with security issues"...
Right.  You do what needs to be done so we don't make it easy for the bad guys.  That counts as a trump card...
