### ISSUE TITLE
a problem when convert my Elekta infinity logfiles to csv files

### ISSUE THREAD

**Issue by daliDuans** [pymedphys/pymedphys#1822]
Dear SimonBiggs, I have a problem when convert my Elekta infinity logfiles to csv files. Could you help me solve my problem? Thank you very much! The bug reports and the trf file to be converted were attached as following,

bug reports:
![Fig1](https://github.com/pymedphys/pymedphys/assets/152958108/d355c64b-a681-4799-900a-513d213659a8)

trf file:
[24_01_27 11_41_01 Z AR_AR.zip](https://github.com/pymedphys/pymedphys/files/14137899/24_01_27.11_41_01.Z.AR_AR.zip)

**Comment by SimonBiggs** [comment]
Could you copy your error message in as text into this issue so that other's can find this via Google search?

**Comment by SimonBiggs** [comment]
@mchamberland do you know if you might be in a position to help @daliDuans ?

**Comment by daliDuans** [comment]
yes, the error message was as following:

D:\log>pymedphys trf to-csv *.trf
{'34': 'State Code Unknown', '39': 'Move Only', '40': 'Pause', '41': 'Intersegment', '42': 'Radiation On', '43': 'Interupted', '44': 'Interupted Ready', '45': 'Terminated Checking', '46': 'Terminated Ok', '47': 'Terminated Fault'}
(array([2442], dtype=int64),)
[16]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Scripts\pymedphys.exe\__main__.py", line 7, in <module>
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\cli\__init__.py", line 148, in pymedphys_cli
    args.func(args)
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\trf2csv.py", line 84, in trf2csv_cli
    trf2csv(filepath)
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\trf2csv.py", line 64, in trf2csv
    dataframes["header"], dataframes["table"] = trf2pandas(trf_filepath)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\trf2pandas.py", line 61, in trf2pandas
    table_dataframe = decode_trf_table(trf_table_contents, header_dataframe)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\table.py", line 37, in decode_trf_table
    table_dataframe = convert_data_table(
                      ^^^^^^^^^^^^^^^^^^^
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\table.py", line 230, in convert_data_table
    dataframe = convert_linac_state_codes(dataframe, linac_state_codes)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\table.py", line 129, in convert_linac_state_codes
    dataframe[key] = convert_numbers_to_string(name, linac_state_codes, dataframe[key])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\44439\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymedphys\_trf\decode\table.py", line 115, in convert_numbers_to_string
    raise ValueError(
ValueError: The conversion lookup list for converting linac state is incomplete. The following data numbers were not converted:
[16]
Please update the trf2csv conversion script to include these in its definitions.

D:\log>

**Comment by daliDuans** [comment]
@SimonBiggs  Could you help solve my issue? thank you!

**Comment by SimonBiggs** [comment]
To fix this you'll need to find out what Linac state 16 means and then submit a PR to add it to the following file:
https://github.com/pymedphys/pymedphys/blob/7ebae3a7d3d31fc2be952801edd4137871e3be93/lib/pymedphys/_trf/decode/config.json#L3-L14

**Comment by daliDuans** [comment]
Dear SimonBiggs, i find the linac state 16, as showed in the follow figure. However, i do not know how to submit a PR to the file you mentioned. @SimonBiggs 
<img width="275" alt="状态编码1" src="https://github.com/pymedphys/pymedphys/assets/152958108/c591137f-e3c2-42db-8842-79d8d8b0b945">

**Comment by SimonBiggs** [comment]
Go to https://claude.ai, copy the above text in, and ask Claude to teach
you how to make a PR on GitHub using the GitHub interface, then follow the
steps it tells you :)

**Comment by daliDuans** [comment]
Thank you! i have created a PR on GitHub. please review it.

**Comment by daliDuans** [comment]
Thank you! i have created a PR on GitHub. please review it. @SimonBiggs

**Comment by sjswerdloff** [comment]
> Thank you! i have created a PR on GitHub. please review it. @SimonBiggs

I'm running the tests against this.
Assuming the tests pass, I'll approve and merge.

**Comment by thanhtaiphys** [comment]
@daliDuans Hi, could you tell me how to export logfiles from Elekta infinity?
