### ISSUE TITLE
MetersetMap Comparison

### ISSUE THREAD

**Issue by KARAjihane** [pymedphys/pymedphys#1841]
Hello,
I've been trying to run the example in the meter set map comparison, but I keep encountering an error whenever I attempt to perform the calculation. Despite my efforts, I can't seem to figure out what's causing the issue. Could you please provide assistance?
<img width="625" alt="Capture d’écran 2024-03-24 131416" src="https://github.com/pymedphys/pymedphys/assets/164746996/a410acdd-c815-42b0-b31c-6090f9e2ed3a">
<img width="697" alt="Capture d’écran 2024-03-24 131726" src="https://github.com/pymedphys/pymedphys/assets/164746996/ed84616f-073d-4563-8e80-2a87612d50d0">
<img width="650" alt="Capture d’écran 2024-03-24 131731" src="https://github.com/pymedphys/pymedphys/assets/164746996/90abc474-f477-45e8-9b0a-733e86b9ec44">

**Comment by SimonBiggs** [comment]
Might you be able to copy the error message text into this issue?

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, this seems related to you new gamma changes?

**Comment by SimonBiggs** [comment]
@KARAjihane as a first step to get yourself unblocked might you be able to revert to the previous version:

`pip install "pymedphys[user]==0.39.3"`

**Comment by Matthew-Jennings** [comment]
I'll try to take a look this evening.

**Comment by KARAjihane** [comment]
Now i can't launch the gui, everytime i try i get this message :
Traceback (most recent call last):
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_vendor\apipkg\__init__.py", line 238, in __getattribute__
    return getattr(getmod(), name)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_vendor\apipkg\__init__.py", line 216, in getmod
    x = importobj(modpath, None)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_vendor\apipkg\__init__.py", line 103, in importobj
    module = __import__(modpath, None, None, ["__doc__"])
ModuleNotFoundError: No module named 'streamlit.bootstrap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\Scripts\pymedphys.exe\__main__.py", line 7, in <module>
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\cli\__init__.py", line 148, in pymedphys_cli
    args.func(args)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_gui.py", line 44, in main
    start.start_streamlit_server(streamlit_script_path, config)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_streamlit\server\start.py", line 26, in start_streamlit_server
    st.bootstrap.load_config_options(flag_options=config)
  File "C:\Users\insim\anaconda3\envs\pymedphys_envi\lib\site-packages\pymedphys\_vendor\apipkg\__init__.py", line 248, in __getattribute__
    raise ModuleNotFoundError(
ModuleNotFoundError:
                    PyMedPhys was unable to import "streamlit.bootstrap.load_config_options".
                    The easiest way to fix this issue is to use the "[user]"
                    option when installing PyMedPhys. For example,
                    with pip this can be done by calling
                    "pip install pymedphys[user]==0.39.3".

**Comment by KARAjihane** [comment]
i tries this command : pip install streamlit
pip install altair==4.2.0
pip install imageio==2.22.1
and now it's working! 
I am grateful for your assistance.

**Comment by SimonBiggs** [comment]
Glad it worked :)

**Comment by SimonBiggs** [comment]
I don't believe this is actually fixed. The "fix" I suggest was to not use the version that has your accelerated gamma changes

**Comment by Matthew-Jennings** [comment]
Sorry I misinterpreted @KARAjihane's reply. I thought the manual dependency installs were while using 0.40.0. Thanks for picking that up.

**Comment by zism** [comment]
Hi, can we use iCom log from mosaiq instead of TRF logfile?

**Comment by SimonBiggs** [comment]
Yes, this software is set up to use TRF or iCOM

**Comment by sjswerdloff** [comment]
> Hi, can we use iCom log from mosaiq instead of TRF logfile?

Do you mean the iCOM file that pymedphys generates?  If so, yes.
If you mean the log file from the VMI on a MOSAIQ SEQUENCER, no.  That isn't an iCOM log (it contains information about iCOM communication, but it isn't the same thing as the file that pymedphys generates from listening in on iCOM communication).

**Comment by SarraBg02** [comment]
is there any way to  transform the VMI log files into those generated by pymedphys

**Comment by SimonBiggs** [comment]
@SarraBg02, I'm not sure what's in the VMI logs, but my suspicion is no? The iCOM data stream is very rich, I doubt unless something was explicitly trying to log this it wouldn't be able to create a 1:1 mapping

**Comment by SimonBiggs** [comment]
Depending what you want though, you can get very similar information from the TRFs that are stored whenever you take a backup
